# Generated by Django 5.0.6 on 2024-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(null=True, upload_to='Media/featured_img')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
